language: java
sudo: required
dist: trusty

# Install mongo 2.6. Note that we change the port to 27000; the tests are
# hardcoded to connect to mongo on that port.
before_install:
 - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10"
 - "echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list"
 - "sudo apt-get update"
 - "sudo apt-get install mongodb-org-server mongodb-org-shell mongodb-org-tools"
 - "echo 'port=27000' | sudo tee -a /etc/mongod.conf"
 - "sudo service mongod restart"

